### ISSUE TITLE
[Question] Way to disable extra platform icon?

### ISSUE THREAD

**Issue by yodaluca23** [Bulldog3321/Bulldogs-Theme#2]
Is their a way I can disable the extra platform icon, next to a user's PFP?

ScreenShots:
![image](https://user-images.githubusercontent.com/67206487/229969785-ac7ae87d-49dd-460e-866f-f4ebe00d6798.png)
![229968827-b0b54ee9-a1dd-4355-8fa9-0d363f2315f6](https://user-images.githubusercontent.com/67206487/229971123-9ea41b67-163e-439c-846e-a48606f5f307.png)

**Comment by Bulldog3321** [comment]
`#app-mount .wrapper-3Un6-K foreignObject[mask*=mobile]:after {
  display: none !important;
}`

**Comment by yodaluca23** [comment]
With all the changes this seems to not be working anymore, is their a new snippet?
