### ISSUE TITLE
Glitches with Vencord USRBG

### ISSUE THREAD

**Issue by yodaluca23** [Bulldog3321/Bulldogs-Theme#3]
Cause text misplacement and bg misplacement, check attached screenshots.

ScreenShots:
![image](https://user-images.githubusercontent.com/67206487/232634548-27d30e1d-2296-44d8-8749-77f1c18b0ac5.png)
![image](https://user-images.githubusercontent.com/67206487/232634583-aa9979f0-f8bc-4a85-913c-56bbfbd86ef7.png)
![image](https://user-images.githubusercontent.com/67206487/232634609-df7c2f8a-a832-43d2-b78d-a53a1c2010e1.png)
![image](https://user-images.githubusercontent.com/67206487/232634627-21a4d543-3018-4243-878b-d064d01f2661.png)

**Comment by Bulldog3321** [comment]
fixed
