### ISSUE TITLE
Vencord Plugin Compatibility Enhancements & other general improvments

### ISSUE THREAD

**Issue by yodaluca23** [Bulldog3321/Bulldogs-Theme#5]
Some things I've noticed that conflict or could use some improvement upon with Vencord Plugins, also some general improvements. I understand if you can't, or don't have time to do all/any of these, but I figured I'd report them here in case. I also want to thank you for this amazing theme, I absolutely love it.

Glitching text username in the bottom left of the full profile view:
![image](https://github.com/Bulldog3321/Bulldogs-Theme/assets/67206487/99aa959d-d129-4c51-936c-2a6f7300ca85)

Icon for new common group DMs tab Vencord Plugin in full profile view:
![image](https://github.com/Bulldog3321/Bulldogs-Theme/assets/67206487/da1eff0b-5e8b-41ce-aed8-1bd28763a8f4)

Status can invade on Badges area in full profile view:
![image](https://github.com/Bulldog3321/Bulldogs-Theme/assets/67206487/f10c6975-fa5c-405a-8776-8e5c2ea1882c)

The status is very close to the edge of the scrollable area and could use some more padding in the mini profile view:
![image](https://github.com/Bulldog3321/Bulldogs-Theme/assets/67206487/749e80ba-0662-49e4-a75d-3b28057b5521)

Pronouns could use some more styling in the mini profile view:
![image](https://github.com/Bulldog3321/Bulldogs-Theme/assets/67206487/f866aa43-cd01-4e15-b775-9b420970fa7d)

Discord Developer Settings Icons (I know they used to be here... idk what happened to them...):
![image](https://github.com/Bulldog3321/Bulldogs-Theme/assets/67206487/18490c42-3206-46f2-af16-62e7cbdf5245)

The username plate in full profile view might look better if it didn't go out of the image, you may want to simply put the username underneath the PFP or something...:
![image](https://github.com/Bulldog3321/Bulldogs-Theme/assets/67206487/1d43f74d-4828-4b6e-ba06-5416736818d2)

Shrink the padding on the play/pause, skip, etc icons in the Spotify Controls plugin as they run into each other and the time stamps:
![image](https://github.com/Bulldog3321/Bulldogs-Theme/assets/67206487/5a967b58-f05c-461b-8804-66b714281c00)

Again, I just can't thank you enough for this theme, and completely understand if you can't act on all of these requests.

**Comment by Bulldog3321** [comment]
[fixed](https://github.com/Bulldog3321/Bulldogs-Theme/commit/c759ba9f3fca33b9041d2cad92f8872e05da7803) everything i could. the [settings icons](https://github.com/CreArts-Community/Settings-Icons) arent made by me so i wont be fixing them.

**Comment by yodaluca23** [comment]
> [fixed](https://github.com/Bulldog3321/Bulldogs-Theme/commit/c759ba9f3fca33b9041d2cad92f8872e05da7803) everything i could. the [settings icons](https://github.com/CreArts-Community/Settings-Icons) arent made by me so i wont be fixing them.

Thanks, I'll take a look 🙂
