### ISSUE TITLE
Discord broke (almost) everything

### ISSUE THREAD

**Issue by yodaluca23** [Bulldog3321/Bulldogs-Theme#6]
The latest update to the stable branch of Discord, broke essentially all themes, and client mods, snipet from Vencord Discord server:
```
Many themes are broken

Hi! Discord recently pushed an update that changed a lot of their css classes. As such, many themes are semi or fully broken

If your theme is broken, just wait, or use a different theme for the time being. Don't complain in ⁠🏥-support-🏥, we can't help you

They now pushed this update to stable.

All themes are broken (theme devs need to fix them)

A lot of plugins are broken

Please be patient, while we fix it. We'll start working on it tomorrow, but it might take a few days considering a looot of stuff has broken

if you're running into issues or crashes, i recommend just uninstalling vencord for now, until we fixed the rest 

and no, this is not discord trying to kill mods. please do not spread misinformation.

they heavily changed their build configuration, which makes their output code a lot more clean and modern, which should also improve performance. this is a good update, both for them and for us. it's only a temporary setback.
```

Nothing in this theme works anymore, except for the background color, and the smaller window bar. Hope you can get this fixed :)

Also, btw, when it was working, the close minimize and move button colors was taking up the full area, instead of just the curved box like they used too....

**Comment by Bulldog3321** [comment]
💀💀💀

**Comment by yodaluca23** [comment]
@Bulldog3321 Just want to say, that I really appreciate your work! Most of the theme seems to be fixed, the only thing I've noticed, is when in DMs, it seems the 'x' to close out a DM is taking up the whole DM button, except a tiny sliver off to the left...

https://github.com/Bulldog3321/Bulldogs-Theme/assets/67206487/a6f5116d-7e5f-457f-a5bb-c5e7a85dcf4d

**Comment by Bulldog3321** [comment]
thanks! fixed this and a few more things

**Comment by yodaluca23** [comment]
Don't know when or why this happened, but It wasn't like this before...
![image](https://github.com/Bulldog3321/Bulldogs-Theme/assets/67206487/618b762b-b2b3-4908-a947-07b07a244fe1)
(This is in the mini profile view.)

**Comment by yodaluca23** [comment]
I found these weird glitches, the Spotify playing in the activities tab in full profile view is scrunched up, and the rounded corners is all different...
![image](https://github.com/Bulldog3321/Bulldogs-Theme/assets/67206487/6dea8008-def8-460e-accb-cafd71cf51a3)


Also, I really like the new settings panel thing, but it's weird that you can interact with some things behind it but not others... Again thanks for all your work!

**Comment by yodaluca23** [comment]
Theirs these weird lines in forum channels:
![image](https://github.com/Bulldog3321/Bulldogs-Theme/assets/67206487/16d483e4-c0ca-46b3-8058-6c6ecf021523)

And if you could make it so that when you click outside of the settings menu it closes that'd be useful.

**Comment by yodaluca23** [comment]
A similar thing just happened 😥 Not as many things are broken this time around though.
Announcement from Vencord Server:
```
Discord pushed a big update that broke a looot of themes and many Vencord plugins.

Vencord has completely been fixed. Update your Vencord via the Updater tab, or by repairing with the installer

The chrome browser extension update is pending. Wait for Google to approve. Use the Userscript or Discord Desktop / Vesktop for now or just wait.

 Many themes are still gonna be broken, wait for your theme dev to fix them or use a different theme or https://vencord.dev/plugins/ClientTheme
```
